package com.wakilfly.dto.response;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Upload Ticket – unique ID generated by backend.
 * Client uses this uploadId for all subsequent chunk requests and complete.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ChunkStartResponse {

    /** Unique upload ID – use this for all chunk and complete requests */
    private String uploadId;

    /** Echo of requested filename (for client verification) */
    private String filename;

    /** Total chunks expected */
    private Integer totalChunks;
}
